// Generates src/media.ts: a curated set of the marketing site's MASTER
// photos, resized and inlined as data-URIs so the design system travels
// with real Nellie imagery (the components and previews default to these,
// so anything the design agent builds uses the brand's own photography,
// never deck or stock images). Resizing keeps the bundle sane: full-res
// marketing photos would bloat it to many megabytes.
//
// Uses macOS `sips` (always present on darwin) so there's no image-library
// dependency. Re-run any time the master set changes: it's deterministic.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const IMG = join(root, '..', 'nellie', 'images');

// key -> { file, max width in px }. Chosen to give the agent good coverage:
// device/hero, lifestyle + portraits for circles, app UI for screens,
// feature scenes. Widths are tuned per use so each stays light.
const SET = [
  { key: 'heroDevice',        file: 'hero-v4.jpg',                  max: 1100 },
  { key: 'productTablet',     file: 'product-tablet.png',           max: 720 },
  { key: 'grandmaGrandkids',  file: 'grandma-grandchildren.jpg',    max: 900 },
  { key: 'whoIsNellieFor',    file: 'who-is-nellie-for.jpg',        max: 1000 },
  { key: 'familyBig',         file: 'hiw-family-big.jpg',           max: 1000 },
  { key: 'manBeforeNellie',   file: 'male-before-nellie.jpg',       max: 760 },
  { key: 'portraitFemale',    file: 'Female-3.png',                 max: 640 },
  { key: 'portraitNorma',     file: 'norma.png',                    max: 640 },
  { key: 'circleOne',         file: 'hiw-circle-1.jpg',             max: 640 },
  { key: 'circleTwo',         file: 'hiw-circle-2.jpg',             max: 640 },
  { key: 'circleThree',       file: 'hiw-circle-3.jpg',             max: 640 },
  { key: 'insights',          file: 'hiw-insights.jpg',             max: 900 },
  { key: 'bringFamilyCloser', file: 'Pricing-Bring_Family_Closer.jpg', max: 1000 },
  { key: 'appPhotos',         file: 'app-1.png',                    max: 480 },
  { key: 'appReminders',      file: 'app-3.png',                    max: 480 },
  { key: 'sceneSlideshows',   file: 'carousel-photo-slideshows.jpg', max: 760 },
];

const mime = (f) => (/\.png$/i.test(f) ? 'image/png' : 'image/jpeg');

const tmp = mkdtempSync(join(tmpdir(), 'nellie-media-'));
const entries = [];
for (const { key, file, max } of SET) {
  const src = join(IMG, file);
  const out = join(tmp, key + extname(file));
  try {
    execFileSync('sips', ['-Z', String(max), src, '--out', out], { stdio: 'ignore' });
    const b64 = readFileSync(out).toString('base64');
    entries.push(`  ${key}: "data:${mime(file)};base64,${b64}",`);
    console.log(`  ${key.padEnd(20)} <- ${file}`);
  } catch (e) {
    console.error(`  SKIP ${key} (${file}): ${e.message}`);
  }
}
rmSync(tmp, { recursive: true, force: true });

const banner = `// GENERATED by gen-media.mjs from nellie/images/ master photos. Do not edit by hand.\n` +
  `// These are the brand's own photographs, inlined so designs built with this\n` +
  `// system use real Nellie imagery. Re-run \`npm run gen:media\` to refresh.\n`;
// An explicit MediaKey union + Record type keeps the keys typed without the
// huge `as const` literal (which TS refuses to serialize for big strings).
const keyUnion = SET.map((s) => `'${s.key}'`).join(' | ');
writeFileSync(
  join(root, 'src', 'media.ts'),
  `${banner}\nexport type MediaKey = ${keyUnion};\n\n` +
  `export const media: Record<MediaKey, string> = {\n${entries.join('\n')}\n};\n`
);
console.log(`\nwrote src/media.ts (${entries.length} images)`);
